[line_break]
disabled = false

add_newline = true

format = """
($username)[//](bold blue)($hostname)
($directory)
"""

right_format = """$all"""

[username]
disabled = false
show_always = true
style_user = "bold yellow"
format = "[$user]($style)"

[hostname]
disabled = false
ssh_only = false
style = "bold red"
format =  "[$hostname]($style)"

[directory]
disabled = false
truncation_length = 1
home_symbol = "[~] "
format = "(bold green)[ @ ](bold blue)[$path](bold purple)(bold green) "

[character]
success_symbol = "[îª¶îª¶](bold purple)"
vimcmd_symbol = "[INS îª¶](bold yellow)"
vimcmd_visual_symbol = "[VIS îª¶](bold yellow)"
error_symbol = "[ERR îª¶](bold red)"

[git_branch]
symbol = "îœ¥ "
style = "bold blue"

[git_commit]
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[git_metrics]
added_style = "bold blue"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold cyan"
conflicted = "= "
ahead = " â‡¡ ${count} "
behind = " â‡£ ${count} "
diverged = " â‡• "
up_to_date = " ï˜³  "
untracked = "? "
stashed = " $ "
modified = " ! "
staged = '[++\($count\)](green)'
renamed = "Â» "
deleted = " ï€ "

[cmd_duration]
disabled = false
